name: Create a S3 Bucket

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  creating_butckets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: tfdocs

      - name: Terraform Plan
        env:
          BUTCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          terraform plan -var="bucket_name=$BUCKET_NAME"
        working-directory: tfdocs
     
      - name: Terraform Apply
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform apply -auto-approve
        working-directory: tfdocs
    
      - name: Upload Files to S3 Bucket
        run: |
          aws s3 cp index.html s3://${{ secrets.BUCKET_NAME }}
          aws s3 cp --recursive css s3://${{ secrets.BUCKET_NAME }}/css/


        

